### ISSUE TITLE
omnipay/common: 3.0

### ISSUE THREAD

**Issue by webdevgr** [digitickets/omnipay-cardlink#2]
This package require omnipay/common: ~2.0 and doesn't install with omnipay/common: 3.0

**Comment by pedanticantic** [comment]
Hi Gerasimos, sorry for the slight delay in replying.
Obviously I don't know your system or what packages & versions you're using, but I do know why you're getting that error.
A little background: as you know, Omnipay is a framework for payment gateway processing, and people write drivers for it for specific gateways. Now, the important thing with regard to your problem is that there are two versions of the Omnipay framework - version 2 and version 3. They are _not_ compatible with each other. All gateway drivers on your system must use the same version as each other - ie all must use version 2 or all must use version 3.
I assume there is a reason why you are using version 3 (I'm guessing you have other drivers that require it, or maybe you just chose to go with the latest version - which is sensible).
If you have to use v3, I'm afraid you will not be able to use this driver.
If you can downgrade to v2, then you will be able to use it.

I'm not sure what the differences are between v2 and v3 (I've never used v3), but one option would be for you to fork this repo and modify it to make it compatible with v3.
